Fixed exception caused by misused of LogPrintf()
************************
EXCEPTION: St13runtime_error
tinyformat: Not enough conversion specifiers in format string
bitcoin in addcon